//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotes
    {
        public int NoteId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public string ObjectType { get; set; }
        public string IsPrivate { get; set; }
    
        public virtual User User { get; set; }
    }
}
